resources:

  - name: ndwrepo
    type: gitRepo
    # replace dr_github with your GitHub integration name
    integration: github
    pointer:
      # replace with source code location (e.g. GitHub) where you cloned this
      # sample project.
      sourceName: ambarish2012/node-docker-windows
      branch: master

jobs:

  - name: build_node_image
    type: runSh
    runtime:
      nodePool: custom__x86_64__WindowsServer_2016
    steps:
      - IN: ndwrepo
      - TASK:
          name: build_image
          runtime:
            container: false
          script:
            - pushd $env:NDWREPO_STATE
            - docker build -t mynodeapp:latest .
            - docker run -d -p 9080:8080 --name mynodeapp mynodeapp:latest
            - sleep 5
            - curl 172.31.83.97:9080
            - docker stop mynodeapp
            - docker rm mynodeapp
            - popd
